import { Montserrat } from "next/font/google";
import "./globals.css";
//component
import Header from "@/components/Header"
import StairTransition from "@/components/StairTransition";
import PageTransition from "@/components/PageTransition"

const montserrat = Montserrat({ subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: '--font-montserrat'
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <Header />
        <PageTransition>
        {children}
        </PageTransition>
        <StairTransition />
      </body>
    </html>
  );
}
